<?
$aMenuLinks = [
    [
        "Партнерам",
        "/partners/postavshchikam-tovarov",
        [],
        [],
        ""
    ],
    [
        "Поставщикам услуг",
        "/partners/postavshchikam-uslug",
        [],
        [],
        ""
    ],
    [
        "Поставщикам товаров",
        "/partners/postavshchikam-tovarov",
        [],
        [],
        ""
    ],
    [
        "Арендодателям",
        "/partners/arendodatelyam",
        [],
        [],
        ""
    ],
    [
        "Франчайзинг",
        "/partners/franchayzing",
        [],
        [],
        ""
    ],
];
?>